In [1]:
import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

print("x_data.shape = ", x_data.shape, "x_data.ndim = ", x_data.ndim)
print("t_data.shape = ", t_data.shape, "t_data.ndim = ", t_data.ndim)

x_data.shape =  (9, 2) x_data.ndim =  2
t_data.shape =  (9, 1) t_data.ndim =  2


In [4]:
W = np.random.rand(2, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.60361442]
 [0.49987617]] , W.shape =  (2, 1) , b =  [0.88336134] , b.shape =  (1,)


In [6]:
def sigmoid(x) :
  return 1 / ( 1 + np.exp(-x) )

In [7]:
def loss_func(x, t) :

  delta = 1e-7

  z = np.dot(x, W) + b
  y = sigmoid(z)

  return -np.sum( t*np.log(y + delta) + (1-t)*np.log((1-y)+delta))


In [8]:
def numerical_derivative(f, x) :
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished :
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2*delta_x)

    x[idx] = tmp_val
    it.iternext()

    return grad

In [12]:
def error_val(x, t) :
  delta = 1e-7

  z = np.dot(x, W) + b
  y = sigmoid(z)

  return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def predict(x) :
  z = np.dot(x, W) + b
  y = sigmoid(z)

  if y >= 0.5 :
    result = 1
  else :
    result = 0

  return y, result


In [13]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initail error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(80001) :

  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0) :
    print("step = ", step, "error value = ", error_val(x_data, t_data), ", W = ", W, ", b = ", b)

Initail error value =  0.08173661363584153 Initial W =  [[2.68765776]
 [0.49987617]] 
 , b =  [-27.07661703]
step =  0 error value =  0.08173581538263949 , W =  [[2.68766763]
 [0.49987617]] , b =  [-27.07670586]
step =  400 error value =  0.0814177626955867 , W =  [[2.69160897]
 [0.49987617]] , b =  [-27.112169]
step =  800 error value =  0.08110218135228206 , W =  [[2.69553495]
 [0.49987617]] , b =  [-27.14749404]
step =  1200 error value =  0.08078904231643586 , W =  [[2.69944569]
 [0.49987617]] , b =  [-27.18268209]
step =  1600 error value =  0.08047831701307362 , W =  [[2.7033413 ]
 [0.49987617]] , b =  [-27.2177342]
step =  2000 error value =  0.08016997731919481 , W =  [[2.70722191]
 [0.49987617]] , b =  [-27.25265146]
step =  2400 error value =  0.07986399555467055 , W =  [[2.71108762]
 [0.49987617]] , b =  [-27.2874349]
step =  2800 error value =  0.079560344473384 , W =  [[2.71493857]
 [0.49987617]] , b =  [-27.32208558]
step =  3200 error value =  0.07925899725456745 , W =  

In [14]:
test_data = np.array([3, 17])
predict(test_data)

(array([8.16892397e-07]), 0)

In [15]:
test_data = np.array([5, 8])
predict(test_data)

(array([6.30658409e-06]), 0)

In [16]:
test_data = np.array([7, 21])
predict(test_data)

(array([0.74406659]), 1)

In [17]:
test_data = np.array([12, 0])
predict(test_data)

(array([0.99901968]), 1)