In [1]:
import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

print("x_data.shape = ", x_data.shape, "x_data.ndim = ", x_data.ndim)
print("t_data.shape = ", t_data.shape, "t_data.ndim = ", t_data.ndim)

x_data.shape =  (9, 2) x_data.ndim =  2
t_data.shape =  (9, 1) t_data.ndim =  2


In [2]:
W = np.random.rand(2, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.22606044]
 [0.04976678]] , W.shape =  (2, 1) , b =  [0.25390984] , b.shape =  (1,)


In [3]:
def sigmoid(x) :
  return 1 / ( 1 + np.exp(-x) )

In [4]:
def loss_func(x, t) :

  delta = 1e-7

  z = np.dot(x, W) + b
  y = sigmoid(z)

  return -np.sum( t*np.log(y + delta) + (1-t)*np.log((1-y)+delta))


In [5]:
def numerical_derivative(f, x) :
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished :
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2*delta_x)

    x[idx] = tmp_val
    it.iternext()

    return grad

In [6]:
def error_val(x, t) :
  delta = 1e-7

  z = np.dot(x, W) + b
  y = sigmoid(z)

  return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def predict(x) :
  z = np.dot(x, W) + b
  y = sigmoid(z)

  if y >= 0.5 :
    result = 1
  else :
    result = 0

  return y, result


In [7]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initail error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(80001) :

  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0) :
    print("step = ", step, "error value = ", error_val(x_data, t_data), ", W = ", W, ", b = ", b)

Initail error value =  7.697501778069297 Initial W =  [[0.22606044]
 [0.04976678]] 
 , b =  [0.25390984]
step =  0 error value =  5.915460598282281 , W =  [[0.06856064]
 [0.04976678]] , b =  [0.23372655]
step =  400 error value =  1.974608759745779 , W =  [[0.39341612]
 [0.04976678]] , b =  [-3.47426626]
step =  800 error value =  1.396682784059972 , W =  [[0.54806563]
 [0.04976678]] , b =  [-4.97458895]
step =  1200 error value =  1.1539576807629035 , W =  [[0.65213382]
 [0.04976678]] , b =  [-5.95389076]
step =  1600 error value =  1.0123740215042756 , W =  [[0.73288968]
 [0.04976678]] , b =  [-6.70304725]
step =  2000 error value =  0.9161159565296115 , W =  [[0.80004924]
 [0.04976678]] , b =  [-7.32105738]
step =  2400 error value =  0.8446703306636595 , W =  [[0.85821194]
 [0.04976678]] , b =  [-7.85356875]
step =  2800 error value =  0.7885627361416636 , W =  [[0.90993186]
 [0.04976678]] , b =  [-8.32548305]
step =  3200 error value =  0.7427436564416342 , W =  [[0.95678107]
 [0.

In [8]:
test_data = np.array([3, 17])
predict(test_data)

(array([3.24353433e-08]), 0)

In [9]:
test_data = np.array([5, 8])
predict(test_data)

(array([8.10561288e-06]), 0)

In [10]:
test_data = np.array([7, 21])
predict(test_data)

(array([0.00601776]), 0)

In [11]:
test_data = np.array([12, 0])
predict(test_data)

(array([0.99984475]), 1)