## 인공지능, 머신러닝, 딥러닝 리뷰

**머신러닝** : 인공지능을 구현하는 하나의 방법으로서 데이터의 특성과 패턴을 학습한 후, 학습 결과를 바탕으로 테스트 데이터에 대한 미래 값을 예측하는 알고리즘

*   **지도학습(Supervised)** : 정답이 주어진 데이터를 이용하여 학습한 후에 테스트 데이터에 대한 미래 결과를 예측하는 방법 - **회귀(Regression)**, **분류(Classification)**
*   **비지도학습(Unsupervised)** : 학습할 데이터에 정답은 없고 입력 값만 있음. 입력 값 자체의 특성과 분포를 파악해서 그룹화 - **군집화(Clustering)**

## 회귀(Regression)와 분류(Classification)


*   **회귀** : **연속적인 값 Continuoous Value** 을 예측하는 것
*   **분류** : **이산적인 값 Discrete Value** 을 얘측하는 것



## 선형회귀(Linear Regression)

**y = Wx + b**

1.   **학습(Learning)** : 트레이닝 데이터를 먼저 분석하고, 그 데이터의 분포를 가장 잘 나태내는 일차함수의 **기울기 W**, **y절편 b**를 찾는 과정
2.   **오차(Error or Loss)** : 정답 t 와 계산 값 y 의 차이
3.   **손실함수(Loss Function or Cost Function)** : 정답 t 와 계산 값 y 의 차이를 모두 더해서 수식으로 나타낸 것. (t-y) 오차의 부호가 플러스(+)와 마이너스(-) 등으로 혼재하기 때문에, 오차의 총합이 0이 나오는 것을 방지하기 위해서 (t-y)을 제곱하여 사용한다. **(평균제곱오차 MSE, Mean Square Error)**
4.   **경사하강법(Gradient Descent Algorithm)** : **가중치 W** 에서 직선의 기울기가 작아지는 방향으로 진행하면서 손실 함수의 최소값을 찾는 알고리즘
5.   **학습률(Learning Rate, ⍺)** : **가중치 W, 바이어스 b** 값의 감소 또는 증가 비율




In [1]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1)
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1)

print(x_data)
print(t_data)
print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


In [2]:
W = np.random.rand(1,1)
b = np.random.rand(1)

print(("W = ", W, ", b = ", b, ", W.shape = ", W.shape, ", b.shape = ", b.shape))

('W = ', array([[0.8686016]]), ', b = ', array([0.27215375]), ', W.shape = ', (1, 1), ', b.shape = ', (1,))


In [3]:
def loss_func(x, t) :
  y = np.dot(x, W) + b

  return ( np.sum( (t-y)**2 )) / (len(x))

In [4]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [5]:
def error_val(x, t) :
  y = np.dot(x, W) + b

  return( np.sum( (t-y)**2 )) / len(x)

def predict(x) :
  y = np.dot(x, W) + b

  return y

In [6]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initail W = ", W, "\n", ", b = ", b)

for step in range(8001) :

  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0) :
    print("step = ", step, ", error value = ", error_val(x_data, t_data), ", W = ", W, ", b= ", b)


Initial error value =  1.2935080656670839 Initail W =  [[0.8686016]] 
 , b =  [0.27215375]
step =  0 , error value =  0.7923055525350607 , W =  [[0.94118003]] , b=  [0.29023987]
step =  400 , error value =  0.005023542302685474 , W =  [[1.04602584]] , b=  [0.83387277]
step =  800 , error value =  0.0003205316979569926 , W =  [[1.01162605]] , b=  [0.95803654]
step =  1200 , error value =  2.045181730434298e-05 , W =  [[1.00293672]] , b=  [0.9894001]
step =  1600 , error value =  1.3049468546054504e-06 , W =  [[1.00074181]] , b=  [0.99732248]
step =  2000 , error value =  8.3263324134221e-08 , W =  [[1.00018738]] , b=  [0.99932366]
step =  2400 , error value =  5.31269233027031e-09 , W =  [[1.00004733]] , b=  [0.99982916]
step =  2800 , error value =  3.389811791620828e-10 , W =  [[1.00001196]] , b=  [0.99995685]
step =  3200 , error value =  2.1629003278895343e-11 , W =  [[1.00000302]] , b=  [0.9999891]
step =  3600 , error value =  1.3800582789229676e-12 , W =  [[1.00000076]] , b=  [0.

In [7]:
predict(43)

array([[44.]])