In [3]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1)
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1)

print(x_data)
print(t_data)
print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


In [4]:
W = np.random.rand(1,1)
b = np.random.rand(1)

print(("W = ", W, ", b = ", b, ", W.shape = ", W.shape, ", b.shape = ", b.shape))

('W = ', array([[0.49810734]]), ', b = ', array([0.58664393]), ', W.shape = ', (1, 1), ', b.shape = ', (1,))


In [5]:
def loss_func(x, t) :
  y = np.dot(x, W) + b

  return ( np.sum( (t-y)**2 )) / (len(x))

In [6]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [7]:
def error_val(x, t) :
  y = np.dot(x, W) + b

  return( np.sum( (t-y)**2 )) / len(x)

def predict(x) :
  y = np.dot(x, W) + b

  return y

In [9]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initail W = ", W, "\n", ", b = ", b)

for step in range(8001) :

  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0) :
    print("step = ", step, ", error value = ", error_val(x_data, t_data), ", W = ", W, ", b= ", b)


Initial error value =  2.5592224296626642 Initail W =  [[0.63332509]] 
 , b =  [0.58664393]
step =  0 , error value =  1.512459876447615 , W =  [[0.73879493]] , b=  [0.61058335]
step =  400 , error value =  0.0011462883256709677 , W =  [[1.02198587]] , b=  [0.92064346]
step =  800 , error value =  7.313997200322864e-05 , W =  [[1.00555359]] , b=  [0.97995467]
step =  1200 , error value =  4.666762615333019e-06 , W =  [[1.00140283]] , b=  [0.99493658]
step =  1600 , error value =  2.9776704463194356e-07 , W =  [[1.00035435]] , b=  [0.99872099]
step =  2000 , error value =  1.8999297838227218e-08 , W =  [[1.00008951]] , b=  [0.99967692]
step =  2400 , error value =  1.2122675254069646e-09 , W =  [[1.00002261]] , b=  [0.99991839]
step =  2800 , error value =  7.734983501506126e-11 , W =  [[1.00000571]] , b=  [0.99997939]
step =  3200 , error value =  4.935376763158189e-12 , W =  [[1.00000144]] , b=  [0.99999479]
step =  3600 , error value =  3.149062156350296e-13 , W =  [[1.00000036]] , b

In [10]:
predict(43)

array([[44.]])