  인간의 **신경망 Neural Network**은 이전의 **뉴런 Neuron**으로부터 입력 신호를 받아 처리하고 다음 뉴런으로 전달하는 구조이다.
  
  뉴런은 입력 신호의 크기에 비례해서 출력 신호를 만들어 주는 것이 아니라, 각각의 입력 신호에 최적의 가중치를 곱한 모든 합이 어느 **임계값 Threshold**에 도달해야만 다음 뉴런으로 출력 신호를 보내는 구조이다.

  입력 신호를 받아서 특정한 임계값을 넘어서야만 출력을 생성하는 함수를 **활성화 함수 Activation Function** 라고 한다.

* **피드포워드 Feed Foward** : 딥러닝에서 입력층부터 출력층으로 데이터를 전달하면서 오차 값을 계사하는 과정

* **은닉층의 개수**와 **각 은닉층의 놓인 노드의 개수**가 많아지면 학습 속도가 느려지기 때문에, 은닉층과 노드의 적절한 개수를 반드시 고려해야 한다. 은닉층의 개수와 각 은닉층에 놓이는 노드 수는 환경과 개발자들의 경험에 의해 결정되는 **하이퍼 파라미터 Hyper Parameter** 이다.



In [1]:
import numpy as np

def sigmoid(x) :
  return 1 / (1 + np.exp(-x))

def numerical_derivative(f, x) :
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished :
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2*delta_x)

    x[idx] = tmp_val
    it.iternext()

  return grad

In [2]:
class LogicGate :

  def __init__(self, gate_name, xdata, tdata) :
    self.name = gate_name

    self.__xdata = xdata.reshape(4,2)
    self.__tdata = tdata.reshape(4,1)

    self.__W2 = np.random.rand(2,6)
    self.__b2 = np.random.rand(6)

    self.__W3 = np.random.rand(6,1)
    self.__b3 = np.random.rand(1)

    self.__learning_rate = 1e-2

    print(self.name + "object is created")

  def feed_forward(self) :
    delta = 1e-7

    z2 = np.dot(self.__xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))

  def loss_val(self) :
    delta = 1e-7

    z2 = np.dot(self.__xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))

  def train(self) :
    f = lambda x : self.feed_forward()

    print("Initial error value = ", self.loss_val())

    for step in range(10001) :
      self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
      self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
      self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
      self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)

      if (step % 400 == 0) :
        print("step = ", step, "error value = ", self.loss_val())

  def predict(self, xdata) :
    z2 = np.dot(xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    if y > 0.5 :
      result = 1
    else :
      result = 0

    return y, result

In [3]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

AND_GATEobject is created
Initial error value =  9.190989089049673
step =  0 error value =  8.877653120251626
step =  400 error value =  2.224849161158335
step =  800 error value =  2.0500292336759625
step =  1200 error value =  1.8142483802394507
step =  1600 error value =  1.515266013923938
step =  2000 error value =  1.1959850541635393
step =  2400 error value =  0.9093989756175566
step =  2800 error value =  0.6838249242525651
step =  3200 error value =  0.5195277205107303
step =  3600 error value =  0.40339912286775015
step =  4000 error value =  0.32121421034434716
step =  4400 error value =  0.26204679623598615
step =  4800 error value =  0.218451302282902
step =  5200 error value =  0.18554342665298681
step =  5600 error value =  0.1601272350788012
step =  6000 error value =  0.14008396688382707
step =  6400 error value =  0.12398130632354984
step =  6800 error value =  0.11082992143473336
step =  7200 error value =  0.09993164248627288
step =  7600 error value =  0.09078360179

In [4]:
print(AND_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(AND_obj.predict(data))

AND_GATE 

(array([0.00122806]), 0)
(array([0.01466001]), 0)
(array([0.01500066]), 0)
(array([0.97422684]), 1)


In [5]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

OR_obj = LogicGate("OR_GATE", xdata, tdata)
OR_obj.train()

OR_GATEobject is created
Initial error value =  2.283748954657661
step =  0 error value =  2.2763029461047597
step =  400 error value =  1.9088811001539048
step =  800 error value =  1.6102230739518393
step =  1200 error value =  1.2258217474902808
step =  1600 error value =  0.8604601195140019
step =  2000 error value =  0.5922590463814775
step =  2400 error value =  0.41813221326259364
step =  2800 error value =  0.3076176197453831
step =  3200 error value =  0.2357595600970463
step =  3600 error value =  0.18717976408618142
step =  4000 error value =  0.15300022888886558
step =  4400 error value =  0.1280675612544862
step =  4800 error value =  0.10930125805797583
step =  5200 error value =  0.09479276777419457
step =  5600 error value =  0.08331672483858825
step =  6000 error value =  0.07405992145470648
step =  6400 error value =  0.06646630482464048
step =  6800 error value =  0.06014537768819429
step =  7200 error value =  0.05481631922198694
step =  7600 error value =  0.050272

In [6]:
print(OR_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(OR_obj.predict(data))

OR_GATE 

(array([0.01892504]), 0)
(array([0.99365047]), 1)
(array([0.99281143]), 1)
(array([0.99973471]), 1)


In [7]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)
NAND_obj.train()

NAND_GATEobject is created
Initial error value =  2.8139191792993934
step =  0 error value =  2.795192965123208
step =  400 error value =  2.2334885158194564
step =  800 error value =  2.1040472206698357
step =  1200 error value =  1.9030919295464845
step =  1600 error value =  1.595198707645134
step =  2000 error value =  1.204708395813254
step =  2400 error value =  0.8481376380602414
step =  2800 error value =  0.6005752338695122
step =  3200 error value =  0.44045109126447757
step =  3600 error value =  0.3348599786820007
step =  4000 error value =  0.2629418128455797
step =  4400 error value =  0.21232715777739658
step =  4800 error value =  0.1755809717789359
step =  5200 error value =  0.14813456683287712
step =  5600 error value =  0.12710797023390857
step =  6000 error value =  0.11063567016256426
step =  6400 error value =  0.09747604521775678
step =  6800 error value =  0.08678101574653055
step =  7200 error value =  0.07795715362999094
step =  7600 error value =  0.07057991

In [8]:
print(NAND_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(NAND_obj.predict(data))

NAND_GATE 

(array([0.99994081]), 1)
(array([0.98899089]), 1)
(array([0.98903409]), 1)
(array([0.02140422]), 0)


In [9]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])

XOR_obj = LogicGate("XOR_GATE", xdata, tdata)
XOR_obj.train()

XOR_GATEobject is created
Initial error value =  5.996660164201473
step =  0 error value =  5.875848950932452
step =  400 error value =  2.7677295395722403
step =  800 error value =  2.7659170574041148
step =  1200 error value =  2.763604632876116
step =  1600 error value =  2.7605600386939932
step =  2000 error value =  2.756449161014558
step =  2400 error value =  2.7507849789393064
step =  2800 error value =  2.742852628242607
step =  3200 error value =  2.731598062056361
step =  3600 error value =  2.7154629097777967
step =  4000 error value =  2.692156764731564
step =  4400 error value =  2.6584321801346027
step =  4800 error value =  2.6101706198303907
step =  5200 error value =  2.5434580893555223
step =  5600 error value =  2.4569799102669703
step =  6000 error value =  2.353926645344336
step =  6400 error value =  2.2405613179640205
step =  6800 error value =  2.1223537845220974
step =  7200 error value =  2.001412493921901
step =  7600 error value =  1.8765825193679604
step =

In [10]:
print(XOR_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(XOR_obj.predict(data))

XOR_GATE 

(array([0.12513973]), 0)
(array([0.77921619]), 1)
(array([0.78695298]), 1)
(array([0.30921933]), 0)
