In [22]:
import numpy as np

def sigmoid(x) :
  return 1 / (1 + np.exp(-x))

def numerical_derivative(f, x) :
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished :
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2*delta_x)

    x[idx] = tmp_val
    it.iternext()

  return grad

In [25]:
class LogicGate :

  def __init__(self, gate_name, xdata, tdata) :
    self.name = gate_name

    self.__xdata = xdata.reshape(4,2)
    self.__tdata = tdata.reshape(4,1)

    self.__W2 = np.random.rand(2,6)
    self.__b2 = np.random.rand(6)

    self.__W3 = np.random.rand(6,1)
    self.__b3 = np.random.rand(1)

    self.__learning_rate = 1e-2

    print(self.name + "object is created")

  def feed_forward(self) :
    delta = 1e-7

    z2 = np.dot(self.__xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))

  def loss_val(self) :
    delta = 1e-7

    z2 = np.dot(self.__xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))

  def train(self) :
    f = lambda x : self.feed_forward()

    print("Initial error value = ", self.loss_val())

    for step in range(10001) :
      self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
      self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
      self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
      self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)

      if (step % 400 == 0) :
        print("step = ", step, "error value = ", self.loss_val())

  def predict(self, xdata) :
    z2 = np.dot(xdata, self.__W2) + self.__b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, self.__W3) + self.__b3
    y = a3 = sigmoid(z3)

    if y > 0.5 :
      result = 1
    else :
      result = 0

    return y, result

In [26]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

AND_GATEobject is created
Initial error value =  8.47261309880074
step =  0 error value =  8.181838557381159
step =  400 error value =  2.1693987691926058
step =  800 error value =  2.0165916149994203
step =  1200 error value =  1.781705942779897
step =  1600 error value =  1.4623343534778348
step =  2000 error value =  1.1251455421711967
step =  2400 error value =  0.8401391708172317
step =  2800 error value =  0.6236245761017569
step =  3200 error value =  0.46756922589529076
step =  3600 error value =  0.3577944404121023
step =  4000 error value =  0.28077085284065917
step =  4400 error value =  0.22605759206589893
step =  4800 error value =  0.18637373216813702
step =  5200 error value =  0.15688094201991398
step =  5600 error value =  0.13441791628393993
step =  6000 error value =  0.11691271331537015
step =  6400 error value =  0.10298724821016712
step =  6800 error value =  0.09170610625058964
step =  7200 error value =  0.08242008109495465
step =  7600 error value =  0.07466855

In [28]:
print(AND_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(AND_obj.predict(data))

AND_GATE 

(array([0.00017887]), 0)
(array([0.01238994]), 0)
(array([0.01215906]), 0)
(array([0.97855288]), 1)


In [29]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

OR_obj = LogicGate("OR_GATE", xdata, tdata)
OR_obj.train()

OR_GATEobject is created
Initial error value =  2.4654297197019
step =  0 error value =  2.4513874749653217
step =  400 error value =  1.845815033903404
step =  800 error value =  1.5815806084961437
step =  1200 error value =  1.2551828559075837
step =  1600 error value =  0.9341466865336345
step =  2000 error value =  0.6767840678735743
step =  2400 error value =  0.49431902468901573
step =  2800 error value =  0.3708657340336099
step =  3200 error value =  0.28727138365509436
step =  3600 error value =  0.22935758142686155
step =  4000 error value =  0.18801388571784258
step =  4400 error value =  0.15759402830164546
step =  4800 error value =  0.13458075008228657
step =  5200 error value =  0.11673606104915925
step =  5600 error value =  0.10259759466710444
step =  6000 error value =  0.0911833373318582
step =  6400 error value =  0.08181640572234884
step =  6800 error value =  0.07401883350835525
step =  7200 error value =  0.06744560462591044
step =  7600 error value =  0.06184265

In [30]:
print(OR_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(OR_obj.predict(data))

OR_GATE 

(array([0.02389824]), 0)
(array([0.99201221]), 1)
(array([0.99225855]), 1)
(array([0.99947195]), 1)


In [31]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)
NAND_obj.train()

NAND_GATEobject is created
Initial error value =  2.410399625413251
step =  0 error value =  2.4064856449219305
step =  400 error value =  2.280487718109538
step =  800 error value =  2.199045876701411
step =  1200 error value =  2.0441793724095847
step =  1600 error value =  1.7237587088823663
step =  2000 error value =  1.3201608423567746
step =  2400 error value =  0.9848627605554248
step =  2800 error value =  0.7297852131659338
step =  3200 error value =  0.5436106937516472
step =  3600 error value =  0.41216235285739744
step =  4000 error value =  0.3202169189216897
step =  4400 error value =  0.2552481915545609
step =  4800 error value =  0.20839617111109315
step =  5200 error value =  0.17378875496568735
step =  5600 error value =  0.14760431615075875
step =  6000 error value =  0.1273428395987536
step =  6400 error value =  0.11134252988058621
step =  6800 error value =  0.0984760332142697
step =  7200 error value =  0.08796190782141619
step =  7600 error value =  0.0792469176

In [32]:
print(NAND_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(NAND_obj.predict(data))

NAND_GATE 

(array([0.99991031]), 1)
(array([0.98814013]), 1)
(array([0.98831293]), 1)
(array([0.02417097]), 0)


In [33]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])

XOR_obj = LogicGate("XOR_GATE", xdata, tdata)
XOR_obj.train()

XOR_GATEobject is created
Initial error value =  7.60180213473504
step =  0 error value =  7.441639461642962
step =  400 error value =  2.7704399273448455
step =  800 error value =  2.7676936996489125
step =  1200 error value =  2.7646796409291796
step =  1600 error value =  2.761066176745124
step =  2000 error value =  2.7564429239428536
step =  2400 error value =  2.7502632706898353
step =  2800 error value =  2.741777463166567
step =  3200 error value =  2.7299548769783435
step =  3600 error value =  2.7133969104341062
step =  4000 error value =  2.6902508459365846
step =  4400 error value =  2.6581784179611936
step =  4800 error value =  2.614557802397605
step =  5200 error value =  2.5572464638175307
step =  5600 error value =  2.485978644843163
step =  6000 error value =  2.4034171702436593
step =  6400 error value =  2.3143767540285065
step =  6800 error value =  2.2235422113927483
step =  7200 error value =  2.1336424169494097
step =  7600 error value =  2.0450121740480482
step

In [34]:
print(XOR_obj.name, "\n")

test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data :
  print(XOR_obj.predict(data))

XOR_GATE 

(array([0.10811469]), 0)
(array([0.74618859]), 1)
(array([0.69883007]), 1)
(array([0.43315063]), 0)
